/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    forceSwcTransforms: true,
    // swcPlugins: [
    //   [
    //     '@graphql-codegen/client-preset-swc-plugin',
    //     { artifactDirectory: './autogenerated/gql', gqlTagName: 'graphql' },
    //   ],
    // ],
  },
};

module.exports = nextConfig;
